
#  sudo apt-get update && sudo apt-get upgrade -y

#  sudo apt-get install openjdk-17-jdk -y
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bank
#    username: root
#    password: 111
#    url: jdbc:mysql://35.225.76.23/bank_cloud
    url: jdbc:mysql://10.0.0.9/bank_cloud
    username: root
    password:  Sabanci@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
    database: mysql
server:
  port: 8888
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    path: /api-docs-ui
    supported-submit-methods: [ ]
